/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ru.balmukanov.productmarketinterface.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2021-03-09")
public enum ProductType implements org.apache.thrift.TEnum {
  CARD(1),
  ACCOUNT(2),
  DEPOSIT(3),
  LOAD(4);

  private final int value;

  private ProductType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static ProductType findByValue(int value) { 
    switch (value) {
      case 1:
        return CARD;
      case 2:
        return ACCOUNT;
      case 3:
        return DEPOSIT;
      case 4:
        return LOAD;
      default:
        return null;
    }
  }
}
